services:
  tappuiadmin:
    container_name: "${NAME}"
    image: "${DOCKER_COMPOSE_IMAGE_NAME}"
    build:
      dockerfile: Dockerfile.tappuiadmin
    # env_file:
    #   - .env-tappuiadmin
    ports:
      - "${DOCKER_PORT}:80"
    # logging:
      # driver: "awslogs"
      # options:
      #   awslogs-region: "${AWS_REGION}"
      #   awslogs-group: ${AWS_LOGS_GROUP}
      #   awslogs-create-group: "true"
      #   tag: "{{.Name}}"
    networks:
      - default

networks:
  default:
    name: "${NAME}-backend"
    driver: bridge
