name: CI pipeline

on:
  push:
    branches:
      - "main"

jobs:
  build_tappui_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - name: Print Git commit hash
      #   run: echo "Git commit hash: ${{ github.sha }}"
      - name: Build the Docker image for tappui
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u 091219920 -p AyCvsX3TfcAm5NYV
          docker build . --file Dockerfile.tappui --tag 091219920/tappui:lll
          docker push 091219920/tappui:lll

  build_tappuiadmin_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - name: Print Git commit hash
      #   run: echo "Git commit hash: ${{ github.sha }}"
      - name: Build the Docker image for tappuiadmin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u 091219920 -p AyCvsX3TfcAm5NYV
          docker build . --file Dockerfile.tappuiadmin --tag 091219920/tappuiadmin:lll
          docker push 091219920/tappuiadmin:lll

  build_tappweb_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - name: Print Git commit hash
      #   run: echo "Git commit hash: ${{ github.sha }}"
      - name: Build the Docker image for tappweb
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u 091219920 -p AyCvsX3TfcAm5NYV
          docker build . --file Dockerfile.tappweb --tag 091219920/tappweb:lll
          docker push 091219920/tappweb:lll
