name: CD pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

  # push:
  #   branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: sudo docker pull 091219920/tappuiadmin:latest
      - name: Delete old docker container
        run: sudo rm -f github-action-tappuiadmin-1 || true
      - name: Run Docker container
        run: |
          NAME=tappstruiadmin
          AWS_REGION=us-east-1
          AWS_LOGS_GROUP=github
          DOCKER_PORT=9002
          DOCKER_COMPOSE_IMAGE_NAME=91219920/tappuiadmin:latest
          docker compose -f /var/www/github-action/tappuiadmin.docker-compose.yml up -d
          

