name: CI pipeline

on:
  push:
    branches:
      - "main"

jobs:
  build_tappui_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - name: Print Git commit hash
      #   run: echo "Git commit hash: ${{ github.sha }}"
      - name: Build the Docker image for tappui
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          if [[ -n "$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'apps/tappui')" ]]; then
            # Only deploy when changes are made inside the specified folder
            docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
            docker build . --file Dockerfile.tappui --tag 091219920/tappui:lll
            docker push 091219920/tappui:lll
          else
            echo "No changes in the specified folder. Skipping deployment."
          fi
          

  build_tappuiadmin_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Git commit hash
        run: echo "COMMIT_HASH=${{ github.sha }}" >> $GITHUB_ENV

      - name: Check for changes in specified folder
        id: check_changes
        run: |
          git fetch origin 
          CHANGED_FILES=$(git diff --name-status "HEAD^" HEAD | grep -E '^(A|M)\s+apps/tappuiadmin/')
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Deploy Docker Compose
        env:
          DOCKER_COMPOSE_IMAGE_NAME: 091219920/tappui:latest
        run: |
          # if [[ -n "${{ steps.check_changes.outputs.changed_files }}" ]]; then
          #   # Only deploy when new files are added or existing files are modified in the specified folder
            docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
            docker build . --file Dockerfile.tappuiadmin --tag 091219920/tappuiadmin:$COMMIT_HASH --build-arg GIT_COMMIT=$COMMIT_HASH
            docker push 091219920/tappuiadmin:$COMMIT_HASH
          # else
          #   echo "No relevant changes in the specified folder. Skipping deployment."
          # fi         

  build_tappweb_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Print Git commit hash
        run: echo "COMMIT_HASH=${{ github.sha }}" >> $GITHUB_ENV
      # - name: Print Git commit hash
      #   run: echo "Git commit hash: ${{ github.sha }}"
      - name: Build the Docker image for tappweb
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # if [[ -n "$(git diff --name-status ${{ github.event.before }} ${{ github.sha }} | grep -E 'apps/tappweb/')" ]]; then
          #   # Only deploy when new files are added or existing files are modified in the specified folder
            docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
            docker build . --file Dockerfile.tappweb --tag 091219920/tappweb:$COMMIT_HASH --build-arg GIT_COMMIT=$COMMIT_HASH
            docker push 091219920/tappweb:$COMMIT_HASH
          # else
          #   echo "No relevant changes in the specified folder. Skipping deployment."
          # fi
