name: test pipeline

on:
  push:
    branches:
      - main

jobs:
  build_tappui_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Print Git commit hash
        run: echo "COMMIT_HASH=${{ github.sha }}" >> $GITHUB_ENV