# name: test pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build_tappuiadmin_image:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
#       - name: Print Git commit hash
#         run: echo "COMMIT_HASH=${{ github.sha }}" >> $GITHUB_ENV

#       - name: Build the Docker image for tappuiadmin
#         env:
#           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#         run: |
#           docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
#           docker build . --file Dockerfile.tappuiadmin --tag 091219920/tappuiadmin:$COMMIT_HASH --build-arg GIT_COMMIT=$COMMIT_HASH
#           docker push 091219920/tappuiadmin:$COMMIT_HASH


name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy to Server
        run: |
          ssh ubuntu@ec2-18-233-131-68.compute-1.amazonaws.com "cd /var/www/tappstr"

